GET https://bcn-fem-tech-http-store1-danit.herokuapp.com/products
Accept: application/json

###
POST https://bcn-fem-tech-http-store1-danit.herokuapp.com/products
Content-Type: application/x-www-form-urlencoded

name=LotionAfterSun&price=10

###



